package server

import (
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/wow-look-at-my/webhook-runner/internal/server/dashboard"
)

func getDashboard(t *testing.T, s *Server, path string) *httptest.ResponseRecorder {
	t.Helper()
	req := httptest.NewRequest(http.MethodGet, path, nil)
	rec := httptest.NewRecorder()
	admin(s).ServeHTTP(rec, req)
	return rec
}

// index.html must never be cached (it is the deploy switch: it names the
// current hashed asset URLs) and must actually reference them.
func TestDashboardIndexNoCacheAndHashedRefs(t *testing.T) {
	s, _, _, _ := newTestServer(t)
	rec := getDashboard(t, s, "/")
	require.Equal(t, http.StatusOK, rec.Code)
	assert.Equal(t, "no-cache", rec.Header().Get("Cache-Control"))

	body := rec.Body.String()
	assert.Contains(t, body, `"`+dashboard.CSS.HashedName+`"`, "index must reference the hashed CSS URL")
	assert.Contains(t, body, `"`+dashboard.JS.HashedName+`"`, "index must reference the hashed JS URL")
	assert.Contains(t, body, `"`+dashboard.TimelineJS.HashedName+`"`, "index must reference the hashed timeline JS URL")
	assert.NotContains(t, body, `"dashboard.css"`, "bare CSS reference must be rewritten")
	assert.NotContains(t, body, `"dashboard.js"`, "bare JS reference must be rewritten")
	assert.NotContains(t, body, `"timeline.js"`, "bare timeline JS reference must be rewritten")
}

// The timeline is the primary runs view: the custom element ships in the
// markup, the old runs table is demoted (hidden until the toggle reveals
// it), and the served bundle is the generated ts0 output — the DO-NOT-EDIT
// marker is what CI's freshness diff protects.
func TestDashboardTimelinePrimaryRunsView(t *testing.T) {
	s, _, _, _ := newTestServer(t)
	rec := getDashboard(t, s, "/")
	require.Equal(t, http.StatusOK, rec.Code)

	body := rec.Body.String()
	assert.Contains(t, body, `<timeline-view id="runs-timeline">`,
		"the timeline element must ship in the overview markup")
	assert.Contains(t, body, `<section id="runs-section" hidden>`,
		"the runs table must ship demoted (timeline is the primary view)")
	assert.Contains(t, body, `id="timeline-table-toggle"`,
		"the table must stay reachable via the toggle")
	assert.Contains(t, string(dashboard.TimelineJS.Body), "Code generated by ts0",
		"timeline.js must be the generated bundle, not a hand-written file")
}

// The per-hook drill-down view must be invisible on the plain overview.
// Two halves, both load-bearing: the shipped markup carries the hidden
// attribute (so the drill-down is hidden before dashboard.js runs), and the
// CSS carries a [hidden]{display:none !important} guard — the hidden
// attribute's UA rule loses to any author display: on the same element
// (main { display: grid } is what regressed it), so without the guard the
// drill-down renders, empty, stacked below the overview.
func TestDashboardDrilldownHiddenOnOverview(t *testing.T) {
	s, _, _, _ := newTestServer(t)
	rec := getDashboard(t, s, "/")
	require.Equal(t, http.StatusOK, rec.Code)

	assert.Contains(t, rec.Body.String(), `<main id="app-view" hidden>`,
		"initial markup must ship the drill-down view hidden")
	css := string(dashboard.CSS.Body)
	assert.Contains(t, css, "[hidden] { display: none !important; }",
		"CSS must guard the hidden attribute against author display rules")
}

// The drill-down cards must contain their content. An unbreakable value (a
// long trigger path, an image tag, a run id — or adjacent env-var <code>
// chips, which have no whitespace between them and so no soft-wrap
// opportunity at all) used to escape its fixed-width card sideways, and the
// neighboring card's opaque panel painted over the escaped text (grid items
// paint atomically in DOM order). Assert the CSS keeps the wrap/shrink
// guards, and that the JS shows the hook path instead of a trigger URL
// fabricated from location.origin — the dashboard lives on the ADMIN
// port/hostname, hooks are served on the hook port, so such a URL is
// copyable but wrong.
func TestDashboardDrilldownOverflowGuardsAndTriggerPath(t *testing.T) {
	css := string(dashboard.CSS.Body)
	for _, guard := range []string{
		".app-cards > section, .app-cards dd { min-width: 0; }",
		".app-cards dd { overflow-wrap: anywhere; }",
		".chips { display: flex; flex-wrap: wrap;",
		"td { overflow-wrap: anywhere; }",
	} {
		assert.Contains(t, css, guard, "CSS must keep the card overflow guard")
	}
	js := string(dashboard.JS.Body)
	assert.NotContains(t, js, "location.origin}/hook/",
		"trigger endpoints must be shown as paths — hooks are not served on the admin origin")
	assert.Contains(t, js, "(on the hook port)",
		"the trigger path must say which port actually serves it")
}

// The content-addressed URLs are immutable-cacheable: their content can
// never change (a new build changes the hash, and with it the URL).
func TestDashboardHashedAssetsImmutable(t *testing.T) {
	s, _, _, _ := newTestServer(t)
	for _, a := range []dashboard.Asset{dashboard.CSS, dashboard.JS, dashboard.TimelineJS} {
		rec := getDashboard(t, s, "/"+a.HashedName)
		require.Equal(t, http.StatusOK, rec.Code, a.HashedName)
		assert.Equal(t, string(a.Body), rec.Body.String(), "hashed URL must serve the exact embedded bytes")
		assert.Equal(t, "public, max-age=31536000, immutable", rec.Header().Get("Cache-Control"))
		assert.Equal(t, `"`+a.Hash+`"`, rec.Header().Get("ETag"))
		assert.Equal(t, a.ContentType, rec.Header().Get("Content-Type"))
	}
}

// Conditional revalidation: If-None-Match against the ETag answers 304.
func TestDashboardAssetConditionalGet(t *testing.T) {
	s, _, _, _ := newTestServer(t)
	for _, a := range []dashboard.Asset{dashboard.CSS, dashboard.TimelineJS} {
		req := httptest.NewRequest(http.MethodGet, "/"+a.HashedName, nil)
		req.Header.Set("If-None-Match", `"`+a.Hash+`"`)
		rec := httptest.NewRecorder()
		admin(s).ServeHTTP(rec, req)
		require.Equal(t, http.StatusNotModified, rec.Code, a.HashedName)
	}
}

// A hashed path with a stale/wrong hash must 404 — never serve current
// content under an old URL, or an edge cache would keep it alive forever.
func TestDashboardStaleHash404(t *testing.T) {
	s, _, _, _ := newTestServer(t)
	for _, p := range []string{"/dashboard.000000000000.css", "/dashboard.feedfacefeed.js", "/timeline.feedfacefeed.js"} {
		rec := getDashboard(t, s, p)
		require.Equal(t, http.StatusNotFound, rec.Code, p)
	}
}

// The bare (pre-hashing) asset paths keep working for compat, but explicitly
// no-cache: Cloudflare caches .css/.js by extension when the origin is
// silent, which is exactly how the stale-assets incident happened.
func TestDashboardBareAssetsNoCache(t *testing.T) {
	s, _, _, _ := newTestServer(t)
	for p, a := range map[string]dashboard.Asset{
		"/dashboard.css": dashboard.CSS,
		"/dashboard.js":  dashboard.JS,
		"/timeline.js":   dashboard.TimelineJS,
	} {
		rec := getDashboard(t, s, p)
		require.Equal(t, http.StatusOK, rec.Code, p)
		assert.Equal(t, "no-cache", rec.Header().Get("Cache-Control"), p)
		assert.Equal(t, string(a.Body), rec.Body.String(), p)
	}
}
