package ts0gen

import (
	"github.com/stretchr/testify/assert"
	"path/filepath"
	"strings"
	"testing"
)

func TestTS0URL(t *testing.T) {
	got := ts0URL(2, "linux", "amd64")
	want := "https://dl.pazer.build/ts0?v=2&os=linux&arch=amd64"
	assert.Equal(t, want, got)

	// ts0 is platform-neutral (any-platform alias on buildhost), so other
	// GOOS/GOARCH values pass straight through.
	got = ts0URL(7, "darwin", "arm64")
	want = "https://dl.pazer.build/ts0?v=7&os=darwin&arch=arm64"
	assert.Equal(t, want, got)

}

func TestTS0CachePath(t *testing.T) {
	got := ts0CachePath("/home/u/.cache", 2)
	want := filepath.Join("/home/u/.cache", "webhook-runner-ts0", "v2", "ts0.cjs")
	assert.Equal(t, want, got)

	// The .cjs extension is load-bearing (ESM mis-parse otherwise) — keep it.
	assert.Equal(t, ".cjs", filepath.Ext(got))

}

func TestNodeMajor(t *testing.T) {
	cases := []struct {
		in      string
		want    int
		wantErr bool
	}{
		{"v22.22.2\n", 22, false},
		{"v9.1.0", 9, false},
		{"22.0.0", 22, false},
		{"not-a-version", 0, true},
		{"", 0, true},
	}
	for _, c := range cases {
		got, err := nodeMajor(c.in)
		if c.wantErr {
			assert.NotNil(t, err)

			continue
		}
		assert.Nil(t, err)

		assert.Equal(t, c.want, got)

	}
}

func TestDeclHeader(t *testing.T) {
	h := declHeader("https://example.com/x.d.ts", "2026-07-13")
	for _, want := range []string{
		"Code generated by ts0gen",
		"DO NOT EDIT",
		"// Source: https://example.com/x.d.ts\n",
		fetchedPrefix + "2026-07-13",
	} {
		assert.Contains(t, h, want)

	}
	assert.True(t, strings.HasSuffix(h, "\n\n"))

}

func TestSameIgnoringFetchDate(t *testing.T) {
	a := []byte(declHeader("https://example.com/x.d.ts", "2026-07-13") + "export const x = 1;\n")
	b := []byte(declHeader("https://example.com/x.d.ts", "2026-08-01") + "export const x = 1;\n")
	assert.True(t, sameIgnoringFetchDate(a, b))

	assert.True(t, sameIgnoringFetchDate(a, a))

	c := []byte(declHeader("https://example.com/x.d.ts", "2026-07-13") + "export const x = 2;\n")
	assert.False(t, sameIgnoringFetchDate(a, c))

	d := []byte(declHeader("https://example.com/OTHER.d.ts", "2026-07-13") + "export const x = 1;\n")
	assert.False(t, sameIgnoringFetchDate(a, d))

}
