package schema

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
)

// hook.schema.json and manager.schema.json are GENERATED from src/, and the
// reason is a bug this repo already shipped: the two documents declared 24 of
// the same properties, hand-copied, and drifted. The manager's `timeout` lost
// the hook's `^[0-9]+(ns|us|ms|s|m|h)+$` pattern, so "banana" validated;
// api_key_header and enable lost their defaults; run_title lost its examples.
// Every one of those was a copy that stopped matching its twin, silently.
//
// So the shared CONSTRAINTS live once, in src/common.json. What legitimately
// differs per entity is the prose -- all 24 descriptions are entity-specific
// -- so each overlay supplies its own, and a shared key with no description in
// an overlay is an error rather than an undocumented field.
//
// Generated rather than $ref'd across files on purpose: the published schemas
// are fetched by editors and by the hooks repo's CI at a canonical URL, and a
// cross-file $ref would make every consumer fetch a second document to
// validate one manifest.

// overlay is an entity's src/<entity>.json: the whole schema document except
// the shared properties, plus the per-entity prose for them.
type overlay struct {
	Descriptions map[string]string          `json:"descriptions"`
	Properties   map[string]json.RawMessage `json:"properties"`
	// Rest carries every other top-level key ($id, title, required, oneOf,
	// ...) through untouched, so adding one to a source file needs no
	// change here.
	Rest map[string]json.RawMessage `json:"-"`
}

// Generate assembles one published schema from the shared base and an entity
// overlay. base and doc are the raw src/common.json and src/<entity>.json.
func Generate(base, doc []byte) ([]byte, error) {
	var common map[string]json.RawMessage
	if err := json.Unmarshal(base, &common); err != nil {
		return nil, fmt.Errorf("common.json: %w", err)
	}
	var rest map[string]json.RawMessage
	if err := json.Unmarshal(doc, &rest); err != nil {
		return nil, fmt.Errorf("overlay: %w", err)
	}
	var ov overlay
	if err := json.Unmarshal(doc, &ov); err != nil {
		return nil, fmt.Errorf("overlay: %w", err)
	}
	delete(rest, "descriptions")
	delete(rest, "properties")

	props := map[string]json.RawMessage{}
	for name, def := range ov.Properties {
		if _, clash := common[name]; clash {
			// An entity redefining a shared property is the twin coming
			// back: it would silently win over the base.
			return nil, fmt.Errorf("property %q is declared in both common.json and the overlay", name)
		}
		props[name] = def
	}
	for name, def := range common {
		desc, ok := ov.Descriptions[name]
		if !ok {
			return nil, fmt.Errorf("shared property %q has no description in this overlay", name)
		}
		merged, err := withDescription(def, desc)
		if err != nil {
			return nil, fmt.Errorf("property %q: %w", name, err)
		}
		props[name] = merged
	}
	for name := range ov.Descriptions {
		if _, ok := common[name]; !ok {
			return nil, fmt.Errorf("description for %q, which is not a shared property", name)
		}
	}

	encoded, err := encodeObject(props)
	if err != nil {
		return nil, err
	}
	rest["properties"] = encoded
	out, err := encodeObject(rest)
	if err != nil {
		return nil, err
	}
	return append(out, '\n'), nil
}

// withDescription puts the entity's prose in front of the shared constraints,
// which is where a reader expects it.
func withDescription(def json.RawMessage, desc string) (json.RawMessage, error) {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(def, &fields); err != nil {
		return nil, err
	}
	if _, ok := fields["description"]; ok {
		return nil, fmt.Errorf("common.json carries a description; prose belongs in the overlays")
	}
	encodedDesc, err := json.Marshal(desc)
	if err != nil {
		return nil, err
	}
	fields["description"] = encodedDesc
	return encodeObject(fields)
}

// encodeObject writes an object with sorted keys and no HTML escaping, so the
// generated bytes are a pure function of the sources.
func encodeObject(fields map[string]json.RawMessage) ([]byte, error) {
	names := make([]string, 0, len(fields))
	for name := range fields {
		names = append(names, name)
	}
	sort.Strings(names)

	var buf bytes.Buffer
	buf.WriteByte('{')
	for i, name := range names {
		if i > 0 {
			buf.WriteByte(',')
		}
		key, err := json.Marshal(name)
		if err != nil {
			return nil, err
		}
		buf.Write(key)
		buf.WriteByte(':')
		buf.Write(fields[name])
	}
	buf.WriteByte('}')

	var pretty bytes.Buffer
	if err := json.Indent(&pretty, buf.Bytes(), "", "  "); err != nil {
		return nil, err
	}
	return pretty.Bytes(), nil
}
