name: JIT Runner Image

on:
  push:
    branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wow-look-at-my/actions@ghcr#latest
        with:
          build_dockerfile: jit-runner.Dockerfile
          push_image: ghcr.io/wow-look-at-my/jit-runner:latest
